services:
  - docker

matrix:
  fast_finish: true

before_script:
  - make build

script:
  - make test

after_success:
  - if [[ "${TRAVIS_TAG}" != "" ]]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker tag udovicic/magepack:2.8 udovicic/magepack:latest;
    docker tag udovicic/magepack:2.8 udovicic/magepack:${TRAVIS_TAG};
    docker push udovicic/magepack:2.8;
    docker push udovicic/magepack:latest;
    docker push udovicic/magepack:${TRAVIS_TAG};
    fi
